Auto merge dependabot
DDDEastMidlandsLimited/dddem-web pull request #807
Opened 2022-07-08 16:06 UTC by johnnolan

### Description of the Change

* Enables auto merge of dependabot builds.
* Refactors common build steps
* Add nvm to use v16 of node

Fixes #806

2022-07-18 10:26 UTC, wordshaker requested changes

2022-07-18 10:26 UTC, wordshaker commented on .github/workflows/dependabot-approve-and-auto-merge_job.yml
> +        if: ${{ steps.dependabot-metadata.outputs.update-type != 'version-update:semver-major' }}
good! I was going to comment not to auto-merge majors but you beat me to it

2022-07-18 10:26 UTC, wordshaker commented on .github/workflows/dependabot-approve-and-auto-merge_job.yml
> +
What about other checks? I'm thinking mostly of the Snyk scan. It that part of the build breaks I wouldn't want the PR automerged, but that works as a plugin.

2022-07-18 12:45 UTC, johnnolan commented on .github/workflows/dependabot-approve-and-auto-merge_job.yml
> +
It looks like we can replace the plugin for an action version, you alright for me to do that so we have better control in our pipelines? https://github.com/marketplace/actions/snyk

2022-07-19 16:43 UTC, johnnolan commented on .github/workflows/dependabot-approve-and-auto-merge_job.yml
> +
Hold on I am overthinking this, synk is required to pass in the checks, this will still respect that and won't skip past it so we are safe as it is

2022-07-19 16:55 UTC, johnnolan commented
After this it still **may** not auto merge without one of us approving it. But once you approve the PR it handles the merging and deletion of the PR making it way less stress.

If you want it fully automatic then we may need to add dependabot as a user to the repo, but that can be done at any time in the future if we feel comfortable.

2022-07-22 11:21 UTC, wordshaker approved these changes

2022-07-22 11:22 UTC, merged